# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('address', models.TextField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='session.Profile')),
            ],
        ),
    ]
