# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('all_day', models.BooleanField(default=False, verbose_name='All day')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Weight')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('date_of_impregnation', models.DateField(blank=True, null=True, verbose_name='Date of Impregnation')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('notes', models.TextField(blank=True, max_length=256, null=True, verbose_name='Notes')),
                ('gender', models.IntegerField(choices=[(0, 'Stallion'), (1, 'Mare')], default=0, verbose_name='Gender')),
                ('pregnant', models.IntegerField(choices=[(0, 'Not Pregnant'), (1, 'Pregnant')], default=0, verbose_name='Pregnant')),
                ('sold', models.BooleanField(default=False, verbose_name='Sold')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Sale Price')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=256, verbose_name='Details')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequency')),
                ('interval', models.IntegerField(blank=True, choices=[(0, 'Weeks'), (1, 'Months'), (2, 'Years')], null=True, verbose_name='Interval')),
                ('classification', models.PositiveIntegerField(blank=True, choices=[(3, 'All'), (0, 'Foals'), (1, 'Adults'), (2, 'Pregnant Mares')], null=True, verbose_name='Demographic')),
                ('doses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Doses')),
                ('date_to_start', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(default=0, verbose_name='Frequency')),
                ('interval', models.IntegerField(choices=[(0, 'Weeks'), (1, 'Months'), (2, 'Years')], verbose_name='Interval')),
                ('classification', models.PositiveIntegerField(choices=[(3, 'All'), (0, 'Foals'), (1, 'Adults'), (2, 'Pregnant Mares')], verbose_name='Demographic')),
                ('doses', models.PositiveIntegerField(default=0, verbose_name='Doses')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='records.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('horse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='history', serialize=False, to='records.Horse')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='horse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_medicines', to='records.Horse'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='horses',
            field=models.ManyToManyField(to='records.Horse'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='session.Profile'),
        ),
        migrations.AddField(
            model_name='horse',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='farms.Farm'),
        ),
        migrations.AddField(
            model_name='horse',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='session.Profile'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.Horse'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.Medicine'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='session.Profile'),
        ),
        migrations.AddField(
            model_name='medicalevent',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.MedicalHistory'),
        ),
    ]
