# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('all_day', models.BooleanField(default=False, verbose_name='All day')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Weight')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('notes', models.TextField(max_length=256, verbose_name='Notes')),
                ('gender', models.IntegerField(choices=[(0, 'Stallion'), (1, 'Mare')], default=0, verbose_name='Gender')),
                ('pregnant', models.IntegerField(choices=[(0, 'Not Pregnant'), (1, 'Pregnant')], default=0, verbose_name='Pregnant')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('notes', models.TextField(max_length=256)),
                ('horses', models.ManyToManyField(related_name='medicines', to='records.Horse')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(default=0, verbose_name='Frequency')),
                ('interval', models.IntegerField(choices=[(0, 'Weeks'), (1, 'Months'), (2, 'Years')], verbose_name='Interval')),
                ('classification', models.PositiveIntegerField(choices=[(0, 'Foal'), (1, 'Adult'), (2, 'Pregnant Mare')], verbose_name='Demographic')),
                ('doses', models.PositiveIntegerField(default=0, verbose_name='Doses')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='records.Medicine')),
            ],
        ),
    ]
