# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20170725_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='birth',
            field=models.BooleanField(default=False, verbose_name='Birth Event'),
        ),
    ]
