# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20170712_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='notes',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Weight'),
        ),
    ]
