# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20170713_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classification',
            field=models.PositiveIntegerField(choices=[(0, 'Foals'), (1, 'Adults'), (2, 'Pregnant Mares')], verbose_name='Demographic'),
        ),
    ]
