# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20170713_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='horses',
            field=models.ManyToManyField(to='records.Horse'),
        ),
    ]
