# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20170713_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.Horse'),
        ),
    ]
