# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_calendarevent_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='date_of_impregnation',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Impregnation'),
        ),
    ]
