# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_horse_date_of_impregnation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='medicine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.Medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='date_to_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
