# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20170721_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='classification',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Foals'), (1, 'Adults'), (2, 'Pregnant Mares')], null=True, verbose_name='Demographic'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='doses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Doses'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(0, 'Weeks'), (1, 'Months'), (2, 'Years')], null=True, verbose_name='Interval'),
        ),
    ]
