# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20170722_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='horse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_medicines', to='records.Horse'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='records.Medicine'),
        ),
    ]
