# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20170722_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='interval',
            field=models.IntegerField(choices=[(0, 'Weeks'), (1, 'Months'), (2, 'Years'), (3, 'All')], verbose_name='Interval'),
        ),
    ]
