# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20170723_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='horse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='history', serialize=False, to='records.Horse'),
        ),
    ]
