# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('records', '0016_auto_20170723_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='farms.Farm'),
        ),
    ]
